+++
date = "2015-07-01T00:00:00+01:00"
title = "Consulting & Training"
type = "services"
aliases = [
	"/training/"
]
+++

If you are interested by any of these opportunities,
mailto:contact@ninenines.eu[send me an email].

== Consulting

You can get me, Loïc Hoguin, author of Cowboy, to help you
solve a problem or work on a particular project.

My area of expertise is Erlang; HTTP, Websocket and REST APIs;
design and implementation of protocols; and messaging systems.

I can also be helpful with testing or code reviews.

I offer both hourly and daily rates:

* 200€ hourly rate (remote)
* 1000€ daily rate (remote and on-site)

For remote consulting, the work can be done by phone, email,
IRC, GitHub and/or any other platform for collaborative work.

For on-site consulting, the travel expenses and
accomodations are to be paid by the customer. I will also
ask for a higher rate if forced to stay on-site for more
than a week.

Note that my expertise does not cover all areas where
Erlang is used. My help will be limited in the areas of
distributed databases, or large distributed systems.

== Sponsoring

You can sponsor one of my projects.

Sponsoring gives you:

* a direct, private line of communication

* the power to make me maintain older versions of my projects
  (as long as they are sponsoring)

* priority when adding features or fixing bugs

* advertisement space on this website and in the README file
  of the project of your choice

Sponsors may choose to benefit from any of these perks.

In exchange sponsors must contribute financially. A minimum
of 200€ per month is required. Sponsors may give as much as
they want. Payment can be monthly or one-time. Invoices are
of course provided.

== Erlang beginner training

I would be happy to introduce more people to Erlang. I have
a 1-day Erlang training readily available for consumption.
The goal of this training is to teach the basics of Erlang
systems and programming. It's a kind of "Getting started"
for Erlang.

You can review the link:/talks/thinking-in-erlang/thinking-in-erlang.html[training slides].

This training is meant to be given to a large number of
people interested in Erlang, as part of a public event,
where anyone interested can come.

Another important aspect of this training is that it is
meant to be affordable. We want the most people to learn
Erlang as possible.

If you have room, think you can gather 20+ people and
are interested in sponsoring a training session, then
we should talk.

== Custom training

I can also provide custom training, tailored to your level
and your needs. It can take the form of a class, Q&A or a
code review/writing session. I need to know your expectations
to prepare an appropriate training.

Custom training rates are the same as consulting rates and
the same restrictions apply.

// @todo Also need the donate link.
