{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @OverheadSetup} } }
}
{@OverheadTransparencies
  \a{Validation using Erlang's type system

with Sheriff}
  \b{sheriff}
  \c{Loïc Hoguin}
  \d{Dev:Extend}
  \e{Yes}
  \j{English}
  \k{Landscape}} } }
}
{@@V @SaveTitle {@@V @InitialLanguage @Language {@@V @RunningTitle @@V @Dft @@V @Title}}} } }
}
{save @@V @StoreTitle
  \a{@@V x}}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @BeginTheoremCounter {}} } }
}
{@@V @TheoremCounterMarker
  \a{"9.2859.all.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @BeginDefinitionCounter {}} } }
}
{@@V @DefinitionCounterMarker
  \a{"9.2918.all.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @BeginClaimCounter {}} } }
}
{@@V @ClaimCounterMarker
  \a{"9.2973.all.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @BeginPropositionCounter {}} } }
}
{@@V @PropositionCounterMarker
  \a{"9.3028.all.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @BeginLemmaCounter {}} } }
}
{@@V @LemmaCounterMarker
  \a{"9.3083.all.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @BeginCorollaryCounter {}} } }
}
{@@V @CorollaryCounterMarker
  \a{"9.3138.all.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @BeginExampleCounter {}} } }
}
{@@V @ExampleCounterMarker
  \a{"9.3193.all.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "63 5"
}
{Yes @BeginDisplayCounter {}} } }
 }
{@@E {
{ @@A { @@E {
@@D "1470 101"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V @NumDispCounterMarker
  \a{"4.1429.all.1"}
  \b{{} @Join 0}}}

{@@E {
@@D "49 4"
}
{@@V @FigurePrefixMarker
  \a{"9.3762.all.1"}
  \b{}}}

{@@E {
@@D "49 4"
}
{@@V @FigureCounterMarker
  \a{"9.3770.all.1"}
  \b{0}}}

{@@E {
@@D "49 4"
}
{@@V @FigurePrefixMarker
  \a{"9.3762.all.2"}
  \b{}}}

{@@E {
@@D "49 4"
}
{@@V @FigureCounterMarker
  \a{"9.3770.all.2"}
  \b{0}}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.1"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @PageList
  \a{1}
  \b{Titles}
  \d{Landscape}
  \c{Yes}
1} } }
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
  \c{Yes}
  \e{@@V @AtTop}
1} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @OverheadSetup} } }
}
{@OverheadTransparencies
  \a{Validation using Erlang's type system

with Sheriff}
  \b{sheriff}
  \c{Loïc Hoguin}
  \d{Dev:Extend}
  \e{Yes}
  \j{English}
  \k{Landscape}} } }
}
{@@V @OverheadsBody} } }
}
{Start @Runner
  \g{"9.952.all.2"}
  \b{@@V @GetTitle}}} }
}
{@PageMarker
  \a{"4.1230.all.1"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{1}
  \c{}
  \d{}}
  \c{1}
  \d{"Odd"}}}

{@@E {
{ @@A { @@E {
@@D "21 2"
}
{@@V @OverheadsBody} } }
}
{Start @Runner
  \g{"9.952.all.2"}
  \b{@@V @GetTitle}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.1"}
  \b{1}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.1"}
  \b{Good Erlang code}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.2"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "2092 155"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
2} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.1"}
  \b{Good Erlang code}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.1"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "3419 263"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "3397 262"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.6"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.2"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{2}
  \c{@Prefix}
  \d{"10.260.all.1"}}
  \c{2}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.1"}
  \b{Good Erlang code}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.1"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "4911 346"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "4889 345"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.6"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.1"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "4925 347"
 }
{@@E {
{ @@A { @@E {
@@D "4925 347"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.1"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "4925 347"
}
{@TitleMarker
  \a{"10.260.all.1"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "4925 347"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "6476 440"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.4"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.1"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.2"}
  \b{2}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.2"}
  \b{Dialyzer is awesome, isn't it?}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.3"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
3} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.2"}
  \b{Dialyzer is awesome, isn't it?}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.2"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "7233 499"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "7211 498"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.9"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.2"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.3"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{3}
  \c{@Prefix}
  \d{"10.260.all.2"}}
  \c{3}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.2"}
  \b{Dialyzer is awesome, isn't it?}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.2"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "8738 582"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "8716 581"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.9"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.2"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "8752 583"
 }
{@@E {
{ @@A { @@E {
@@D "8752 583"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.2"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "8752 583"
}
{@TitleMarker
  \a{"10.260.all.2"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.2"}
  \b{Dialyzer is awesome, isn't it?}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.2"}
  \b{@@V type 1}}}

{@@E {
@@D "10351 679"
}
{@@V listitem
  \a{"4.1748.all.1"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "10337 678"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.4"}
  \b{@@V type 2}}}

{@@E {
@@D "10351 679"
}
{@@V listitem
  \a{"4.1748.all.2"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "10337 678"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.6"}
  \b{@@V type 3}}}

{@@E {
@@D "10351 679"
}
{@@V listitem
  \a{"4.1748.all.3"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "8752 583"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "11131 746"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.7"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.2"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.3"}
  \b{3}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.3"}
  \b{Good Erlang code receiving external data}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.4"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "7071 486"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
4} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.3"}
  \b{Good Erlang code receiving external data}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.3"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "11892 804"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "11870 803"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.12"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.3"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.4"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{4}
  \c{@Prefix}
  \d{"10.260.all.3"}}
  \c{4}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.3"}
  \b{Good Erlang code receiving external data}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.3"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "13411 887"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "13389 886"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.12"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.3"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "13425 888"
 }
{@@E {
{ @@A { @@E {
@@D "13425 888"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.3"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "13425 888"
}
{@TitleMarker
  \a{"10.260.all.3"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "13425 888"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "15006 981"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.10"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.3"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.4"}
  \b{4}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.4"}
  \b{We lost Dialyzer}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.5"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
5} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.4"}
  \b{We lost Dialyzer}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.4"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "15752 1040"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "15730 1039"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.15"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.4"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.5"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{5}
  \c{@Prefix}
  \d{"10.260.all.4"}}
  \c{5}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.4"}
  \b{We lost Dialyzer}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.4"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "17248 1123"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "17226 1122"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.15"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.4"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "17262 1124"
 }
{@@E {
{ @@A { @@E {
@@D "17262 1124"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.4"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "17262 1124"
}
{@TitleMarker
  \a{"10.260.all.4"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.4"}
  \b{We lost Dialyzer}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.8"}
  \b{@@V type 1}}}

{@@E {
@@D "18858 1220"
}
{@@V listitem
  \a{"4.1748.all.4"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "18844 1219"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.10"}
  \b{@@V type 2}}}

{@@E {
@@D "18858 1220"
}
{@@V listitem
  \a{"4.1748.all.5"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "18858 1220"
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.12"}
  \b{@@V type 1}}}

{@@E {
@@D "18858 1220"
}
{@@V listitem
  \a{"4.1748.all.6"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "19424 1269"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.14"}
  \b{@@V type 2}}}

{@@E {
@@D "18858 1220"
}
{@@V listitem
  \a{"4.1748.all.7"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "18844 1219"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.16"}
  \b{@@V type 3}}}

{@@E {
@@D "18858 1220"
}
{@@V listitem
  \a{"4.1748.all.8"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "17262 1124"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "20130 1331"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.13"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.4"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.5"}
  \b{5}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.5"}
  \b{What is external data?}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.6"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "15590 1027"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
6} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.5"}
  \b{What is external data?}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.5"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "20879 1389"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "20857 1388"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.18"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.5"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.6"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{6}
  \c{@Prefix}
  \d{"10.260.all.5"}}
  \c{6}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.5"}
  \b{What is external data?}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.5"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "22382 1472"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "22360 1471"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.18"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.5"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "22396 1473"
 }
{@@E {
{ @@A { @@E {
@@D "22396 1473"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.5"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "22396 1473"
}
{@TitleMarker
  \a{"10.260.all.5"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.5"}
  \b{What is external data?}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.18"}
  \b{@@V type 1}}}

{@@E {
@@D "23998 1569"
}
{@@V listitem
  \a{"4.1748.all.9"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "23984 1568"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.20"}
  \b{@@V type 2}}}

{@@E {
@@D "23998 1569"
}
{@@V listitem
  \a{"4.1748.all.10"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "23998 1569"
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.22"}
  \b{@@V type 1}}}

{@@E {
@@D "23998 1569"
}
{@@V listitem
  \a{"4.1748.all.11"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "24572 1618"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.24"}
  \b{@@V type 2}}}

{@@E {
@@D "23998 1569"
}
{@@V listitem
  \a{"4.1748.all.12"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "24572 1618"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.26"}
  \b{@@V type 3}}}

{@@E {
@@D "23998 1569"
}
{@@V listitem
  \a{"4.1748.all.13"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "24572 1618"
}
{@@V @MakeList 4} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.28"}
  \b{@@V type 4}}}

{@@E {
@@D "23998 1569"
}
{@@V listitem
  \a{"4.1748.all.14"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "23984 1568"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.30"}
  \b{@@V type 3}}}

{@@E {
@@D "23998 1569"
}
{@@V listitem
  \a{"4.1748.all.15"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "22396 1473"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "25737 1720"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.16"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.5"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.6"}
  \b{6}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.6"}
  \b{Why check external data? Just let it crash!}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.7"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
7} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.6"}
  \b{Why check external data? Just let it crash!}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.6"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "26512 1779"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "26490 1778"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.21"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.6"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.7"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{7}
  \c{@Prefix}
  \d{"10.260.all.6"}}
  \c{7}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.6"}
  \b{Why check external data? Just let it crash!}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.6"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "28035 1862"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "28013 1861"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.21"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.6"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "28049 1863"
 }
{@@E {
{ @@A { @@E {
@@D "28049 1863"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.6"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "28049 1863"
}
{@TitleMarker
  \a{"10.260.all.6"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.6"}
  \b{Why check external data? Just let it crash!}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.32"}
  \b{@@V type 1}}}

{@@E {
@@D "29672 1959"
}
{@@V listitem
  \a{"4.1748.all.16"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "29658 1958"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.34"}
  \b{@@V type 2}}}

{@@E {
@@D "29672 1959"
}
{@@V listitem
  \a{"4.1748.all.17"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "29658 1958"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.36"}
  \b{@@V type 3}}}

{@@E {
@@D "29672 1959"
}
{@@V listitem
  \a{"4.1748.all.18"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "29672 1959"
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.38"}
  \b{@@V type 1}}}

{@@E {
@@D "29672 1959"
}
{@@V listitem
  \a{"4.1748.all.19"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "29658 1958"
}
{@@V @MakeList 4} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.40"}
  \b{@@V type 4}}}

{@@E {
@@D "29672 1959"
}
{@@V listitem
  \a{"4.1748.all.20"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "29658 1958"
}
{@@V @MakeList 5} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.42"}
  \b{@@V type 5}}}

{@@E {
@@D "29672 1959"
}
{@@V listitem
  \a{"4.1748.all.21"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "28049 1863"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "31205 2090"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.19"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.6"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.7"}
  \b{7}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.7"}
  \b{Really?}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.8"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "26350 1766"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
8} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.7"}
  \b{Really?}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.7"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "31939 2148"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "31917 2147"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.24"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.7"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.8"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{8}
  \c{@Prefix}
  \d{"10.260.all.7"}}
  \c{8}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.7"}
  \b{Really?}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.7"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "33427 2231"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "33405 2230"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.24"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.7"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "33441 2232"
 }
{@@E {
{ @@A { @@E {
@@D "33441 2232"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.7"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "33441 2232"
}
{@TitleMarker
  \a{"10.260.all.7"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.7"}
  \b{Really?}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.44"}
  \b{@@V type 1}}}

{@@E {
@@D "35028 2328"
}
{@@V listitem
  \a{"4.1748.all.22"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35014 2327"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.46"}
  \b{@@V type 2}}}

{@@E {
@@D "35028 2328"
}
{@@V listitem
  \a{"4.1748.all.23"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35014 2327"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.48"}
  \b{@@V type 3}}}

{@@E {
@@D "35028 2328"
}
{@@V listitem
  \a{"4.1748.all.24"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "33441 2232"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "35796 2395"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.22"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.7"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.8"}
  \b{8}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.8"}
  \b{Always validate external data}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.9"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
9} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.8"}
  \b{Always validate external data}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.8"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "36557 2454"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "36535 2453"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.27"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.8"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.9"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{9}
  \c{@Prefix}
  \d{"10.260.all.8"}}
  \c{9}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.8"}
  \b{Always validate external data}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.8"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "38066 2537"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "38044 2536"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.27"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.8"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "38080 2538"
 }
{@@E {
{ @@A { @@E {
@@D "38080 2538"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.8"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "38080 2538"
}
{@TitleMarker
  \a{"10.260.all.8"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.8"}
  \b{Always validate external data}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.50"}
  \b{@@V type 1}}}

{@@E {
@@D "39689 2634"
}
{@@V listitem
  \a{"4.1748.all.25"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "39689 2634"
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.52"}
  \b{@@V type 1}}}

{@@E {
@@D "39689 2634"
}
{@@V listitem
  \a{"4.1748.all.26"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "39675 2633"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.54"}
  \b{@@V type 2}}}

{@@E {
@@D "39689 2634"
}
{@@V listitem
  \a{"4.1748.all.27"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "39689 2634"
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.56"}
  \b{@@V type 1}}}

{@@E {
@@D "39689 2634"
}
{@@V listitem
  \a{"4.1748.all.28"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "40544 2707"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.58"}
  \b{@@V type 2}}}

{@@E {
@@D "39689 2634"
}
{@@V listitem
  \a{"4.1748.all.29"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "40544 2707"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.60"}
  \b{@@V type 3}}}

{@@E {
@@D "39689 2634"
}
{@@V listitem
  \a{"4.1748.all.30"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "38080 2538"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "41253 2769"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.25"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.8"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.9"}
  \b{9}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.9"}
  \b{Data validation without Sheriff}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.10"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "36395 2441"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
10} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.9"}
  \b{Data validation without Sheriff}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.9"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "42013 2827"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "41991 2826"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.30"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.9"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.10"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{10}
  \c{@Prefix}
  \d{"10.260.all.9"}}
  \c{10}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.9"}
  \b{Data validation without Sheriff}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.9"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "43528 2910"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "43506 2909"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.30"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.9"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "43542 2911"
 }
{@@E {
{ @@A { @@E {
@@D "43542 2911"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.9"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "43542 2911"
}
{@TitleMarker
  \a{"10.260.all.9"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "43542 2911"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "45119 3004"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.28"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.9"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.10"}
  \b{10}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.10"}
  \b{All this has happened before{...}}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.11"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
11} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.10"}
  \b{All this has happened before{...}}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.10"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "45889 3063"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "45867 3062"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.33"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.10"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.11"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{11}
  \c{@Prefix}
  \d{"10.260.all.10"}}
  \c{11}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.10"}
  \b{All this has happened before{...}}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.10"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "47409 3146"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "47387 3145"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.33"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.10"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "47423 3147"
 }
{@@E {
{ @@A { @@E {
@@D "47423 3147"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.10"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "47423 3147"
}
{@TitleMarker
  \a{"10.260.all.10"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.10"}
  \b{All this has happened before{...}}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.62"}
  \b{@@V type 1}}}

{@@E {
@@D "49041 3243"
}
{@@V listitem
  \a{"4.1748.all.31"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "47423 3147"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "49380 3270"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.31"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.10"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.11"}
  \b{11}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.11"}
  \b{And all this will happen again}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.12"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "45726 3050"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
12} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.11"}
  \b{And all this will happen again}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.11"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "50143 3328"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "50121 3327"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.36"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.11"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.12"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{12}
  \c{@Prefix}
  \d{"10.260.all.11"}}
  \c{12}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.11"}
  \b{And all this will happen again}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.11"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "51661 3411"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "51639 3410"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.36"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.11"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "51675 3412"
 }
{@@E {
{ @@A { @@E {
@@D "51675 3412"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.11"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "51675 3412"
}
{@TitleMarker
  \a{"10.260.all.11"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.11"}
  \b{And all this will happen again}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.64"}
  \b{@@V type 1}}}

{@@E {
@@D "53290 3508"
}
{@@V listitem
  \a{"4.1748.all.32"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "53276 3507"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.66"}
  \b{@@V type 2}}}

{@@E {
@@D "53290 3508"
}
{@@V listitem
  \a{"4.1748.all.33"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "53276 3507"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.68"}
  \b{@@V type 3}}}

{@@E {
@@D "53290 3508"
}
{@@V listitem
  \a{"4.1748.all.34"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "51675 3412"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "54082 3575"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.34"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.11"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.12"}
  \b{12}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.12"}
  \b{I can't type}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.13"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
13} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.12"}
  \b{I can't type}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.12"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "54832 3634"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "54810 3633"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.39"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.12"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.13"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{13}
  \c{@Prefix}
  \d{"10.260.all.12"}}
  \c{13}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.12"}
  \b{I can't type}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.12"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "56331 3717"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "56309 3716"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.39"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.12"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "56345 3718"
 }
{@@E {
{ @@A { @@E {
@@D "56345 3718"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.12"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "56345 3718"
}
{@TitleMarker
  \a{"10.260.all.12"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.12"}
  \b{I can't type}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.70"}
  \b{@@V type 1}}}

{@@E {
@@D "57942 3814"
}
{@@V listitem
  \a{"4.1748.all.35"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "56345 3718"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "58260 3841"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.37"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.12"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.13"}
  \b{13}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.13"}
  \b{Who do you call when you need help?}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.14"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "54669 3621"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
14} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.13"}
  \b{Who do you call when you need help?}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.13"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "59028 3899"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "59006 3898"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.42"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.13"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.14"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{14}
  \c{@Prefix}
  \d{"10.260.all.13"}}
  \c{14}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.13"}
  \b{Who do you call when you need help?}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.13"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "60551 3982"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "60529 3981"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.42"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.13"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "60565 3983"
 }
{@@E {
{ @@A { @@E {
@@D "60565 3983"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.13"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "60565 3983"
}
{@TitleMarker
  \a{"10.260.all.13"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "60565 3983"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "62151 4076"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.40"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.13"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.14"}
  \b{14}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.14"}
  \b{I am the law}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.15"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
15} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.14"}
  \b{I am the law}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.14"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "62901 4135"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "62879 4134"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.45"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.14"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.15"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{15}
  \c{@Prefix}
  \d{"10.260.all.14"}}
  \c{15}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.14"}
  \b{I am the law}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.14"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "64400 4218"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "64378 4217"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.45"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.14"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "64414 4219"
 }
{@@E {
{ @@A { @@E {
@@D "64414 4219"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.14"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "64414 4219"
}
{@TitleMarker
  \a{"10.260.all.14"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.14"}
  \b{I am the law}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.72"}
  \b{@@V type 1}}}

{@@E {
@@D "66011 4315"
}
{@@V listitem
  \a{"4.1748.all.36"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "65997 4314"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.74"}
  \b{@@V type 2}}}

{@@E {
@@D "66011 4315"
}
{@@V listitem
  \a{"4.1748.all.37"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "65997 4314"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.76"}
  \b{@@V type 3}}}

{@@E {
@@D "66011 4315"
}
{@@V listitem
  \a{"4.1748.all.38"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "65997 4314"
}
{@@V @MakeList 4} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.78"}
  \b{@@V type 4}}}

{@@E {
@@D "66011 4315"
}
{@@V listitem
  \a{"4.1748.all.39"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "64414 4219"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "67013 4402"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.43"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.14"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.15"}
  \b{15}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.15"}
  \b{Data validation with Sheriff}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.16"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "62738 4122"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
16} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.15"}
  \b{Data validation with Sheriff}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.15"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "67774 4460"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "67752 4459"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.48"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.15"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.16"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{16}
  \c{@Prefix}
  \d{"10.260.all.15"}}
  \c{16}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.15"}
  \b{Data validation with Sheriff}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.15"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "69290 4543"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "69268 4542"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.48"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.15"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "69304 4544"
 }
{@@E {
{ @@A { @@E {
@@D "69304 4544"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.15"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "69304 4544"
}
{@TitleMarker
  \a{"10.260.all.15"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "69304 4544"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "70883 4637"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.46"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.15"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.16"}
  \b{16}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.16"}
  \b{Tuple validation with Sheriff}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.17"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
17} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.16"}
  \b{Tuple validation with Sheriff}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.16"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "71650 4696"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "71628 4695"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.51"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.16"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.17"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{17}
  \c{@Prefix}
  \d{"10.260.all.16"}}
  \c{17}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.16"}
  \b{Tuple validation with Sheriff}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.16"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "73166 4779"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "73144 4778"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.51"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.16"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "73180 4780"
 }
{@@E {
{ @@A { @@E {
@@D "73180 4780"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.16"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "73180 4780"
}
{@TitleMarker
  \a{"10.260.all.16"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "73180 4780"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "74760 4873"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.49"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.16"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.17"}
  \b{17}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.17"}
  \b{Recursive type validation with Sheriff}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.18"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "71487 4683"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
18} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.17"}
  \b{Recursive type validation with Sheriff}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.17"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "75531 4931"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "75509 4930"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.54"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.17"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.18"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{18}
  \c{@Prefix}
  \d{"10.260.all.17"}}
  \c{18}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.17"}
  \b{Recursive type validation with Sheriff}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.17"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "77057 5014"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "77035 5013"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.54"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.17"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "77071 5015"
 }
{@@E {
{ @@A { @@E {
@@D "77071 5015"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.17"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "77071 5015"
}
{@TitleMarker
  \a{"10.260.all.17"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "77071 5015"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "78660 5108"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.52"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.17"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.18"}
  \b{18}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.18"}
  \b{Parameterized type validation with Sheriff}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.19"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
19} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.18"}
  \b{Parameterized type validation with Sheriff}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.18"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "79440 5167"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "79418 5166"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.57"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.18"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.19"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{19}
  \c{@Prefix}
  \d{"10.260.all.18"}}
  \c{19}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.18"}
  \b{Parameterized type validation with Sheriff}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.18"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "80969 5250"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "80947 5249"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.57"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.18"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "80983 5251"
 }
{@@E {
{ @@A { @@E {
@@D "80983 5251"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.18"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "80983 5251"
}
{@TitleMarker
  \a{"10.260.all.18"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "80983 5251"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "82576 5344"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.55"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.18"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.19"}
  \b{19}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.19"}
  \b{Record validation with Sheriff}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.20"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "79277 5154"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
20} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.19"}
  \b{Record validation with Sheriff}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.19"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "83339 5402"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "83317 5401"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.60"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.19"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.20"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{20}
  \c{@Prefix}
  \d{"10.260.all.19"}}
  \c{20}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.19"}
  \b{Record validation with Sheriff}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.19"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "84857 5485"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "84835 5484"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.60"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.19"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "84871 5486"
 }
{@@E {
{ @@A { @@E {
@@D "84871 5486"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.19"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "84871 5486"
}
{@TitleMarker
  \a{"10.260.all.19"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "84871 5486"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "86452 5579"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.58"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.19"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.20"}
  \b{20}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.20"}
  \b{Digging in}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.21"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
21} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.20"}
  \b{Digging in}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.20"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "87200 5638"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "87178 5637"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.63"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.20"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.21"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{21}
  \c{@Prefix}
  \d{"10.260.all.20"}}
  \c{21}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.20"}
  \b{Digging in}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.20"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "88697 5721"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "88675 5720"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.63"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.20"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "88711 5722"
 }
{@@E {
{ @@A { @@E {
@@D "88711 5722"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.20"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "88711 5722"
}
{@TitleMarker
  \a{"10.260.all.20"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.20"}
  \b{Digging in}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.80"}
  \b{@@V type 1}}}

{@@E {
@@D "90306 5818"
}
{@@V listitem
  \a{"4.1748.all.40"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "90292 5817"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.82"}
  \b{@@V type 2}}}

{@@E {
@@D "90306 5818"
}
{@@V listitem
  \a{"4.1748.all.41"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "90292 5817"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.84"}
  \b{@@V type 3}}}

{@@E {
@@D "90306 5818"
}
{@@V listitem
  \a{"4.1748.all.42"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "90292 5817"
}
{@@V @MakeList 4} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.86"}
  \b{@@V type 4}}}

{@@E {
@@D "90306 5818"
}
{@@V listitem
  \a{"4.1748.all.43"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "88711 5722"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "91306 5905"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.61"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.20"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.21"}
  \b{21}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.21"}
  \b{Don't fall into lava}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.22"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "87037 5625"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
22} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.21"}
  \b{Don't fall into lava}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.21"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "92059 5963"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "92037 5962"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.66"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.21"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.22"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{22}
  \c{@Prefix}
  \d{"10.260.all.21"}}
  \c{22}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.21"}
  \b{Don't fall into lava}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.21"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "93567 6046"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "93545 6045"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.66"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.21"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "93581 6047"
 }
{@@E {
{ @@A { @@E {
@@D "93581 6047"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.21"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "93581 6047"
}
{@TitleMarker
  \a{"10.260.all.21"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.21"}
  \b{Don't fall into lava}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.88"}
  \b{@@V type 1}}}

{@@E {
@@D "95186 6143"
}
{@@V listitem
  \a{"4.1748.all.44"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "95172 6142"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.90"}
  \b{@@V type 2}}}

{@@E {
@@D "95186 6143"
}
{@@V listitem
  \a{"4.1748.all.45"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "95186 6143"
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.92"}
  \b{@@V type 1}}}

{@@E {
@@D "95186 6143"
}
{@@V listitem
  \a{"4.1748.all.46"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "95172 6142"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.94"}
  \b{@@V type 3}}}

{@@E {
@@D "95186 6143"
}
{@@V listitem
  \a{"4.1748.all.47"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "95186 6143"
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.96"}
  \b{@@V type 1}}}

{@@E {
@@D "95186 6143"
}
{@@V listitem
  \a{"4.1748.all.48"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "96261 6236"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.98"}
  \b{@@V type 2}}}

{@@E {
@@D "95186 6143"
}
{@@V listitem
  \a{"4.1748.all.49"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "96261 6236"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.100"}
  \b{@@V type 3}}}

{@@E {
@@D "95186 6143"
}
{@@V listitem
  \a{"4.1748.all.50"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "95172 6142"
}
{@@V @MakeList 4} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.102"}
  \b{@@V type 4}}}

{@@E {
@@D "95186 6143"
}
{@@V listitem
  \a{"4.1748.all.51"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "93581 6047"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "97200 6318"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.64"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.21"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.22"}
  \b{22}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.22"}
  \b{Sheriff got deputies}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.23"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
23} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.22"}
  \b{Sheriff got deputies}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.22"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "97958 6377"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "97936 6376"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.69"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.22"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.23"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{23}
  \c{@Prefix}
  \d{"10.260.all.22"}}
  \c{23}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.22"}
  \b{Sheriff got deputies}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.22"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "99465 6460"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "99443 6459"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.69"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.22"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "99479 6461"
 }
{@@E {
{ @@A { @@E {
@@D "99479 6461"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.22"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "99479 6461"
}
{@TitleMarker
  \a{"10.260.all.22"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.22"}
  \b{Sheriff got deputies}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.104"}
  \b{@@V type 1}}}

{@@E {
@@D "101084 6557"
}
{@@V listitem
  \a{"4.1748.all.52"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "101070 6556"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.106"}
  \b{@@V type 2}}}

{@@E {
@@D "101084 6557"
}
{@@V listitem
  \a{"4.1748.all.53"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "101084 6557"
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.108"}
  \b{@@V type 1}}}

{@@E {
@@D "101084 6557"
}
{@@V listitem
  \a{"4.1748.all.54"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "101663 6606"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.110"}
  \b{@@V type 2}}}

{@@E {
@@D "101084 6557"
}
{@@V listitem
  \a{"4.1748.all.55"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "101070 6556"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.112"}
  \b{@@V type 3}}}

{@@E {
@@D "101084 6557"
}
{@@V listitem
  \a{"4.1748.all.56"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "101070 6556"
}
{@@V @MakeList 4} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.114"}
  \b{@@V type 4}}}

{@@E {
@@D "101084 6557"
}
{@@V listitem
  \a{"4.1748.all.57"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "99479 6461"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "102612 6688"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.67"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.22"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.23"}
  \b{23}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.23"}
  \b{To infinity, and beyond!}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.24"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "97795 6364"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
24} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.23"}
  \b{To infinity, and beyond!}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.23"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "103370 6746"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "103348 6745"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.72"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.23"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.24"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{24}
  \c{@Prefix}
  \d{"10.260.all.23"}}
  \c{24}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.23"}
  \b{To infinity, and beyond!}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.23"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "104884 6829"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "104862 6828"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.72"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.23"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "104898 6830"
 }
{@@E {
{ @@A { @@E {
@@D "104898 6830"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.23"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "104898 6830"
}
{@TitleMarker
  \a{"10.260.all.23"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.23"}
  \b{To infinity, and beyond!}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.116"}
  \b{@@V type 1}}}

{@@E {
@@D "106512 6926"
}
{@@V listitem
  \a{"4.1748.all.58"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "106498 6925"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.118"}
  \b{@@V type 2}}}

{@@E {
@@D "106512 6926"
}
{@@V listitem
  \a{"4.1748.all.59"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "106498 6925"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.120"}
  \b{@@V type 3}}}

{@@E {
@@D "106512 6926"
}
{@@V listitem
  \a{"4.1748.all.60"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "106498 6925"
}
{@@V @MakeList 4} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.122"}
  \b{@@V type 4}}}

{@@E {
@@D "106512 6926"
}
{@@V listitem
  \a{"4.1748.all.61"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "104898 6830"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "107537 7013"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.70"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.23"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.24"}
  \b{24}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.24"}
  \b{Wanted}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.25"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
25} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.24"}
  \b{Wanted}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.24"}
  \b{Major}
  \c{}
  \d{Wanted}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "108283 7072"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "108261 7071"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.75"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.24"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.25"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{25}
  \c{@Prefix}
  \d{"10.260.all.24"}}
  \c{25}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.24"}
  \b{Wanted}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.24"}
  \b{Major}
  \c{}
  \d{Wanted}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "109774 7155"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "109752 7154"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.75"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.24"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "109788 7156"
 }
{@@E {
{ @@A { @@E {
@@D "109788 7156"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.24"}
  \b{@@V @ShortNum}}}

{@@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@TitleMarker
  \a{"10.260.all.24"}
  \b{Wanted}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.24"}
  \b{Wanted}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.124"}
  \b{@@V type 1}}}

{@@E {
@@D "111403 7255"
}
{@@V listitem
  \a{"4.1748.all.62"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "111389 7254"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.126"}
  \b{@@V type 2}}}

{@@E {
@@D "111403 7255"
}
{@@V listitem
  \a{"4.1748.all.63"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "111389 7254"
}
{@@V @MakeList 3} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.128"}
  \b{@@V type 3}}}

{@@E {
@@D "111403 7255"
}
{@@V listitem
  \a{"4.1748.all.64"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "111389 7254"
}
{@@V @MakeList 4} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.130"}
  \b{@@V type 4}}}

{@@E {
@@D "111403 7255"
}
{@@V listitem
  \a{"4.1748.all.65"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "111389 7254"
}
{@@V @MakeList 5} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.132"}
  \b{@@V type 5}}}

{@@E {
@@D "111403 7255"
}
{@@V listitem
  \a{"4.1748.all.66"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "111403 7255"
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.134"}
  \b{@@V type 1}}}

{@@E {
@@D "111403 7255"
}
{@@V listitem
  \a{"4.1748.all.67"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "109788 7156"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "112917 7386"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.73"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.24"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.25"}
  \b{25}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.25"}
  \b{Suit up!}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.26"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "108120 7059"
}
{@@V @RunningEvenPageList
  \a{1}
  \b{Titles}
26} } }
}
{@@V @OrdinaryEvenPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.25"}
  \b{Suit up!}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.25"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "113661 7444"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "113639 7443"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.78"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.25"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.26"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{26}
  \c{@Prefix}
  \d{"10.260.all.25"}}
  \c{26}
  \d{"Even"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.25"}
  \b{Suit up!}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.25"}
  \b{Major}
  \c{}
  \d{@@V @Title}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "115159 7527"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "115137 7526"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.78"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.25"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "115173 7528"
 }
{@@E {
{ @@A { @@E {
@@D "115173 7528"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.25"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "115173 7528"
}
{@TitleMarker
  \a{"10.260.all.25"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.25"}
  \b{Suit up!}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.136"}
  \b{@@V type 1}}}

{@@E {
@@D "116771 7624"
}
{@@V listitem
  \a{"4.1748.all.68"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "116757 7623"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.138"}
  \b{@@V type 2}}}

{@@E {
@@D "116771 7624"
}
{@@V listitem
  \a{"4.1748.all.69"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "115173 7528"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "117318 7671"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.76"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.25"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "35 3"
}
{@@V @OverheadsList
  \a{"10.121.all.26"}
  \b{26}}}

{@@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.26"}
  \b{Fin}
{ ??? }}}

{@@E {
@@D "49 4"
}
{@@V @FootNoteCounterMarker
  \a{"9.1551.all.27"}
  \b{0}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @RunningPageList
  \a{1}
  \b{Titles}
  \d{Landscape}
27} } }
}
{@@V @OrdinaryOddPage} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2364 179"
}
{@Overhead
  \a{"10.260.all.26"}
  \b{Fin}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.26"}
  \b{Major}
  \c{}
  \d{Fin}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "118061 7730"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "118039 7729"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.81"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.26"}
  \f{{} @Join @@V @ShortNum}}} }
}
{@PageMarker
  \a{"4.1230.all.27"}
  \b{@@V @MakePageNum
  \a{Arabic}
  \b{27}
  \c{@Prefix}
  \d{"10.260.all.26"}}
  \c{27}
  \d{"Odd"}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.26"}
  \b{Fin}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.260.all.26"}
  \b{Major}
  \c{}
  \d{Fin}
  \u{@@V @GetTitle}
  \e{dft}
  \f{@@V @AboveOverheadGap}
  \g{@@V @OverheadHeadingFont}
  \h{@@V @OverheadHeadingBreak}
  \i{@Num @@V @OverheadHeadingFormat @Body}
  \k{No}
  \l{@@V @OverheadContentsIndent}
  \n{Arabic}
  \o{{@@V @OverheadsList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @OverheadsList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \s{}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  sendheader{@@V @Full @Body}
  innergap{@DisplayGap}
  inrunners{Yes}
{@@V @Format @@V @Body}} } }
}
{@@V @Heading} } }
 }
{@@E {
{ @@A { @@E {
@@D "119546 7813"
}
{@@V sendheader {
//{@@V aboveheadinggap} @@V headingfont @Font {@@V headingbreak @Break {@@V @LongNum @@V headingformat @@V title}}
// @@V @Run @@V @StartIfMajor
// @PageMark @@V tag
//{@DisplayGap} @@V headingtext}} } }
}
{@Body}} }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "119524 7812"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.all.81"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.26"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "119560 7814"
 }
{@@E {
{ @@A { @@E {
@@D "119560 7814"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.260.all.26"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "111256 7242"
}
{@TitleMarker
  \a{"10.260.all.26"}
  \b{Fin}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "35 3"
}
{@Overhead
  \a{"10.260.all.26"}
  \b{Fin}
{ @LInput }} } }
}
{@RawList
  \a{@Bullet}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.all.140"}
  \b{@@V type 1}}}

{@@E {
@@D "121140 7910"
}
{@@V listitem
  \a{"4.1748.all.70"}
???}}

{@@E {
{ @@B { { @@A { @@E {
@@D "119560 7814"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "121451 7937"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.all.79"}
  \a{dft @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{}
  \d{}
  \e{"10.260.all.26"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
@@D "49 4"
}
{Start @Runner
  \g{"9.952.all.1"}}}

